export const EMERGENCY_PROOFS_LOADING = 'EMERGENCY_PROOFS_LOADING';
export const EMERGENCY_PROOFS_SUCCESS = 'EMERGENCY_PROOFS_SUCCESS';
export const EMERGENCY_PROOFS_ERROR = 'EMERGENCY_PROOFS_ERROR';
export const EMERGENCY_PROOFS_CLEAR_RESPONSE =
  'EMERGENCY_PROOFS_CLEAR_RESPONSE';
export const SUBMIT_EMERGENCY_PROOF = 'SUBMIT_EMERGENCY_PROOF';
