export const INCIDENT_REPORTS_LOADING = 'INCIDENT_REPORTS_LOADING';
export const INCIDENT_REPORTS_SUCCESS = 'INCIDENT_REPORTS_SUCCESS';
export const INCIDENT_REPORTS_ERROR = 'INCIDENT_REPORTS_ERROR';
export const INCIDENT_REPORTS_CLEAR_RESPONSE =
  'INCIDENT_REPORTS_CLEAR_RESPONSE';
