export const REQUEST_BACKUP_LOADING = 'REQUEST_BACKUP_LOADING';
export const REQUEST_BACKUP_SUCCESS = 'REQUEST_BACKUP_SUCCESS';
export const REQUEST_BACKUP_ERROR = 'REQUEST_BACKUP_ERROR';
export const REQUEST_BACKUP_CLEAR_RESPONSE = 'REQUEST_BACKUP_CLEAR_RESPONSE';
