export const GET_ALL_USERS = "GET_ALL_USERS";
export const USERS_LOADING = "USERS_LOADING";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_ERROR = "USERS_ERROR";
export const USERS_CLEAR_RESPONSE = "USERS_CLEAR_RESPONSE";
export const REGISTER_USER = "REGISTER_USER";
export const SET_REGISTER_STEP = "SET_REGISTER_STEP";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
